from __future__ import annotations

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """API request containing a question for the chat agent."""

    message: str = Field(
        ...,
        min_length=1,
        examples=["¿Cuál es mi ticket más reciente?"],
        description="Question to answer using stored ticket data.",
    )


class ChatResponse(BaseModel):
    """API response returned by the chat agent."""

    response: str = Field(
        ...,
        examples=["El ticket más reciente es T001."],
        description="Answer generated by the chat agent.",
    )
