"""initial schema

Revision ID: 5c840a1a73a6
Revises: 
Create Date: 2026-07-22 16:46:31.047341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c840a1a73a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_producto'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('supermercado',
    sa.Column('id_supermercado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_supermercado'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('ticket',
    sa.Column('id_ticket', sa.String(length=50), nullable=False),
    sa.Column('id_supermercado', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_supermercado'], ['supermercado.id_supermercado'], ),
    sa.PrimaryKeyConstraint('id_ticket')
    )
    op.create_table('linea_ticket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ticket', sa.String(length=50), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad_valor', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('cantidad_unidad', sa.String(length=20), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['producto.id_producto'], ),
    sa.ForeignKeyConstraint(['id_ticket'], ['ticket.id_ticket'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linea_ticket')
    op.drop_table('ticket')
    op.drop_table('supermercado')
    op.drop_table('producto')
    # ### end Alembic commands ###
